/* QUESTION 1 */

/* import file */
LIBNAME dataLib xlsx'~/my_shared_file_links/yeunjoosong0/PQHS414/Module05/M05_class_data.xlsx';

/* QUESTION 2 */

/* sort datasets */
PROC SORT DATA = dataLib.MODULE00 OUT = sorted00;
	BY STUDENT;
RUN;

PROC SORT DATA = dataLib.MODULE01 OUT = sorted01;
	BY STUDENT;
RUN;

/* merge datasets */
DATA data414;
	MERGE sorted00 sorted01;
	BY STUDENT;
RUN;


/* QUESTION 3 */

PROC SQL;
	CREATE TABLE sql414 as 
	SELECT *
	FROM dataLib.MODULE00, dataLib.MODULE01;
QUIT;


/* QUESTION 4 */
DATA M00_Dnarrow;
	SET dataLib.MODULE00;
	DROP EXPERIENCE_IN_SAS EXPERIENCE_IN_R EXPERIENCE_IN_PYTHON;
	LENGTH LANGUAGE $ 6;
	
	LANGUAGE = "SAS";
	EXPERIENCE = EXPERIENCE_IN_SAS;
	OUTPUT;

	LANGUAGE = "R";
	EXPERIENCE = EXPERIENCE_IN_R;
	OUTPUT;
	
	LANGUAGE = "Python";
	EXPERIENCE = EXPERIENCE_IN_PYTHON;
	OUTPUT;
RUN;


/* QUESTION 5 */

PROC SORT DATA = M00_Dnarrow;
	BY STUDENT;
RUN;

DATA M00_Dwide;
	SET M00_Dnarrow;
	BY STUDENT;
	
	RETAIN EXPERIENCE_IN_SAS EXPERIENCE_IN_R EXPERIENCE_IN_PYTHON;
	KEEP EXPERIENCE_IN_SAS EXPERIENCE_IN_R EXPERIENCE_IN_PYTHON;
	
	IF LANGUAGE = "SAS" THEN EXPERIENCE_IN_SAS = EXPERIENCE;
	ELSE IF LANGUAGE = "R" THEN EXPERIENCE_IN_R = EXPERIENCE;
	ELSE IF LANGUAGE = "Python" THEN EXPERIENCE_IN_PYTHON = EXPERIENCE;
	
	IF last.STUDENT = 1 THEN OUTPUT;
RUN;


/* QUESTION 6 */
PROC TRANSPOSE DATA = dataLib.MODULE00 OUT = M00_Tnarrow 
	(RENAME = (col1= Experience _name_= Language) DROP = _label_);
	BY STUDENT;
	VAR EXPERIENCE_IN_SAS EXPERIENCE_IN_R EXPERIENCE_IN_PYTHON;
RUN;


/* QUESTION 7 */
PROC TRANSPOSE DATA = M00_Tnarrow OUT = M00_Twide (DROP = _name_);
	VAR EXPERIENCE;
	ID LANGUAGE;
	BY STUDENT;
RUN;

